### ISSUE TITLE
oauth2.1 移出 password 模式后 app 第1次登录 如何解决

### ISSUE THREAD

**Issue by sdack-cloud** [xuxiaowei-com-cn/oauth2.1#1]
qq：1397257618

**Comment by xuxiaowei-com-cn** [comment]
可自定义授权模式，如微信小程序授权登录，参考：https://github.com/xuxiaowei-com-cn/spring-boot-starter-wechat-miniprogram

**Comment by xuxiaowei-com-cn** [comment]
QQ群：696503132

**Comment by memoryseven** [comment]
PKCE， webview 跳到security的验证授权页面，跳转后，APP取得CODE，然后置换token

**Comment by memoryseven** [comment]
我从 [spring-authorization-server](https://github.com/spring-projects/spring-authorization-server/issues/882)  看到你的问题

**Comment by memoryseven** [comment]
具体如下：

**Comment by memoryseven** [comment]
APP拼接一个url ******/oauth2/authorize?response_type=code&state=&client_id=****&scope=openid&redirect_uri=*****&code_challenge=*****&code_challenge_method=S256

**Comment by memoryseven** [comment]
然后获取到code  再通过  /oauth2/token 获取accesstoken

**Comment by memoryseven** [comment]
pkce可参考 https://tonyxu-io.github.io/pkce-generator/
